apiVersion: v1
kind: Pod
metadata:
  name: ex01-app
  labels:
    app: ex01-app
spec:
  containers:
    - name: ex01-app
      image: belokana/ex01-app:latest
      ports:
        - containerPort: 8081