apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.pod.name }}
  labels:
    app: {{ .Values.pod.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.pod.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.pod.name }}
    spec:
      containers:
        - name: {{ .Values.pod.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.containerPort }}



#apiVersion: v1
#kind: Pod
#metadata:
#  name: {{ .Values.pod.name }}
#  labels:
#    app: {{ .Values.pod.name }}
#spec:
#  containers:
#    - name: {{ .Values.pod.name }}
#      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
#      ports:
#        - containerPort: {{ .Values.containerPort }}
